apoio/urls.py
from django.urls import path
from . import views

app_name = 'apoio'

urlpatterns = [
    path('', views.index, name='index'),
]

sitePainel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('reunioes.urls')),
    path('', include('apoio.urls')),
]

apoio/models.py
from django.db import models
from django.forms import ValidationError
from djmoney.models.fields import MoneyField

# Create your models here.
from pickle import OBJ
from datetime import date
from django.conf import settings
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal
from django.core.validators import RegexValidator
from django.utils.translation import gettext as _

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

mes_lista = (
    ('1','Jan'),
    ('2','Fev'),
    ('3','Mar'),
    ('4','Abr'),
    ('5','Mai'),
    ('6','Jun'),
    ('7','Jul'),
    ('8','Ago'),
    ('9','Set'),
    ('10','Out'),
    ('11','Nov'),
    ('12','Dez'),
)

def validar_moeda(value):
    if value.amount <= 0:
        raise ValidationError(_("O valor deve ser maior que zero."))

from django.db import models

### Eixo do Plano ###
class EixoPlano(models.Model): # lista com tipos de metas
    nome = models.CharField(_("Tipo"), max_length=255)
    descricao = models.TextField(blank=True, null=True, verbose_name = _("Descrição"))
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Eixo do Plano"

### Ano ###
class Ano(models.Model): # lista com ano
    ano_nr = models.IntegerField(
        verbose_name = _("Ano"),
        default = 2024
        )
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return str(self.ano_nr)
    
    class Meta:
        verbose_name_plural = "Ano"

class TipoPrograma(models.Model): # lista com tipos de programa
    tipo_programa_nm = models.CharField(_("Tipo"), max_length=255)
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.tipo_programa_nm
    
    class Meta:
        verbose_name_plural = "Tipo do Programa"

### Tipo de Ação ###
class TipoAcao(models.Model): # lista com tipos de ação
    tipo_acao_nm = models.CharField(_("Tipo"), max_length=255)
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.tipo_acao_nm
    
    class Meta:
        verbose_name_plural = "Tipo da Ação"

### Indicador ###
class Indicador(models.Model): # lista com tipos de metas
    nome = models.CharField(_("Tipo"), max_length=255)
    sigla = models.CharField(_("Tipo"), max_length=255)
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.sigla
    
    class Meta:
        verbose_name_plural = "Indicador"

### Município ###
class Municipio(models.Model):
    nome = models.CharField(max_length=100, verbose_name = _("Nome do Município"))
    codigo = models.CharField(max_length=7, verbose_name = _("Código do Município"))
    rd = models.CharField(max_length=30, verbose_name = _("Região de Desenvolvimento"), default="-")

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Município"
        permissions = [("can_export_data", "Can Export Data")]

### Bairro ###
class Bairro(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, verbose_name = _("Nome Município"))
    nome = models.CharField(max_length=100, verbose_name = _("Nome do Bairro"))

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Bairro"
        permissions = [("can_export_data", "Can Export Data")]

### Turno ###
class Turno(models.Model):
    nome = models.CharField(max_length=100, verbose_name = _("Nome do Turno"))

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Turno"

### Status ###
class Status(models.Model): # lista com status de metas e etapas
    nome = models.CharField(_("Status"), max_length=255)
    history = HistoricalRecords()

    def publish(self):
        self.published_date = date.today()
        self.save()

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Status"

apoio/views.py
from django.shortcuts import render

from django.views.generic import ListView
from django.http import HttpResponse

def index(request):
    return render(request, 'apoio/index.html')

apoio/templates/apoio/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-WinySjvph6HTMRk5VGT5B5Ri6XEj6gS2V5tu1Q5iF56UAO1ptVToK8DJCnlv3VoGmNRiSyMvQ3G93+U3yXaNnw=="
crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css"
integrity="sha384-+0n0xVW2eSR5Toekz3ZhX0rX6Ua/YOzTMrVXoyM38qcw6jAHU1/GCy5Z2IbrOfZ6" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hub SEGPR</title>

    <style>
                
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
          Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        line-height: 1.5;
        font-size: var(--small-font-size);
        color: var(--clr-black);
        -webkit-font-smoothing: antialiased;
        /* background: var(--clr-light-gray); */
        background: var(--clr-light-gray);
      }
        
        .navbar {
            background-color: #fff;
            padding: 10px 0;
            width: 100%;
        }
        
        .navbar-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
        }
        
        .brand a {
            display: flex;
            align-items: center;
            color: #000; 
            text-decoration: none;
            font-weight: bold;
            font-size: 20px;
        }
        
        .logo {
            max-width: 200px; 
            margin-right: 10px;
            height: auto;
        }

        .logo-container {
            text-align: center;
        }        
        
        .nav-list {
            list-style: none;
            display: flex;
        }
        
        .nav-item {
            margin-right: 20px;
        }
        
        .nav-item a {
            color: #000; 
            text-decoration: none;
        }
        
        .blog-wrapper {
          padding: 15px;
          display: flex;
          flex-direction: row;
          justify-content: center;
          flex-wrap: wrap;
      
          .blog-card {
              transition: 0.3s;
              max-width: 300px;
              margin: 15px;
              background: #fff;
              border: 1px solid #fff;
              text-align: center;
              cursor: pointer;
              overflow: hidden;
      
              &:hover {
                  box-shadow: 0 3px 10px 0 rgba(0, 0, 0, .1);
      
                  .card-img img {
                      opacity: 0.8;
                  }
              }
      
              .card-img {
                  position: relative;
                  text-align: center;
                  background: #007095;
      
                  img {
                      transition: 0.3s;
                      max-height: 100px;
                      width: 100%;
                      border-bottom: 4px solid #007095;
                  }
      
                  &:before {
                      content: '';
                      position: absolute;
                      bottom: -8px;
                      left: 50%;
                      margin-left: -10px;
                      width: 0;
                      height: 0;
                      border-top: solid 10px #007095;
                      border-left: solid 10px transparent;
                      border-right: solid 10px transparent;
                  }
      
                  h1 {
                      position: absolute;
                      margin: 0;
                      font-size: 42px;
                      bottom: 15px;
                      width: 100%;
                      color: #fff;
                      font-family: "Font Awesome 5 Free", sans-serif;
                  }
              }
      
              .card-details {
                  margin-top: 30px;
                  font-family: "Font Awesome 5 Free", sans-serif;
                  color: #3c3c3c;
      
                  span {
                      padding: 0 30px;
                      i {
                          margin-right: 5px;
                      }
                  }
              }
      
              .card-text {
                  padding: 30px 15px;
                  font-family: "Font Awesome 5 Free", sans-serif;
                  line-height: 22px;
              }
      
              .read-more {
                  transition: 0.3s;
                  display: inline;
                  width: auto;
                  text-align: center;
                  background: #007095;
                  color: #fff;
                  padding: 15px;
                  margin-bottom: 30px;
                  font-family: "Font Awesome 5 Free", sans-serif;
                  cursor: pointer;
                  border: none;
                  border-radius: 5px;
                  text-decoration: none;
      
                  a {
                      color: #fff;
                      text-decoration: none;
                  }
      
                  &:hover {
                      background: darken(#5bc0de, 20%);
                  }
              }
          }
      }
      
      @media (max-width: 768px) {
          .blog-wrapper {
              padding: 5px;
          }
      
          .blog-card {
              max-width: 100%;
          }
      }      

    </style>
    
</head>
<body>

    <nav class="navbar">
        <div class="navbar-container">
            <div class="brand">
                <a href="{% url 'apoio:index' %}">
                    <img src="{% static 'apoio/imagens/seplagtransparente_original.png' %}" alt="Logo" class="logo">
                </a>
            </div>
            <ul class="nav-list">
                <li class="nav-item">
                    <a href="{% url 'apoio:index' %}">
                        <i class="fas fa-home"></i> Início
                    </a>
                </li>
                <!-- Adicione mais itens de menu conforme necessário -->
            </ul>
        </div>
    </nav>

    <div class="blog-wrapper">
      <div class="col-md-6">
      <a href="{% url 'admin:planos_plano_changelist' %}" class="card-link">  
      <div class="blog-card">
          <div class="card-img"><img src="{% static 'apoio/imagens/snap_app_seges.png' %}">
            <h1> </h1>
          </div>
            <div class="card-text"><p></p></div>
            <button class="read-more">
                <a href="{% url 'admin:planos_plano_changelist' %}">Planos de Ação</a>
            </button>
        </div>
      </a>
    </div>

    <div class="col-md-6">
      <a href="{% url 'admin:reunioes_reuniao_changelist' %}" class="card-link">  
        <div class="blog-card">
            <div class="card-img"><img src="{% static 'apoio/imagens/snap_app_seges.png' %}">
              <h1> </h1>
            </div>
              <div class="card-text"><p></p></div>
              <button class="read-more">
                  <a href="{% url 'admin:reunioes_reuniao_changelist' %}">Reuniões</a>
              </button>
          </div>
        </a>
      </div>
      
      <div class="col-md-6">
      <a href="https://projesp.seplag.pe.gov.br/apps/argos/" class="card-link">
        <div class="blog-card">
          <div class="card-img"><img src="{% static 'apoio/imagens/snap_app_argos.png' %}">
          <h1> </h1>
          </div>
          <div class="card-text"><p></p></div>
          <button class="read-more">
              <a href="https://projesp.seplag.pe.gov.br/apps/argos/">Argos</a>
          </button>
        </div>
      </a>
    </div>
      </div>
</body>
</html>